title: CV | A jekyll template
description:  A beautiful template for your CV.
logo: "/_data/Author1.tiff" # your photo (or logo) here
url: https://yasalchak.github.io/jekyll-cv-test/
author: Shangzhi Huang
email: ngzhio@gmail.com
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
