title: CV | Testing jekyll template
description: My CV test


# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/2.jpg

url: https://yasalchak.github.io/jekyll-cv-test/
author: Yana
email: ngzhio@gmail.com
baseurl: ""
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier
    - jekyll-seo-tag

exclude:
  - docker-compose.yml
