title: CV | Yana Salchak
description: My CV 


# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/2.jpg

url: https://yasalchak.github.io
author: Yana
email: iana.salchak@griffithuni.edu.au
baseurl: /cv-online
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier
    - jekyll-seo-tag

exclude:
  - docker-compose.yml


show_degree_title: True
