title: CV | A jekyll template
logo: "/assets/2.jpg?raw=true" # your photo (or logo) here 
description:  A beautiful template for your CV.
url: https://yasalchak.github.io/jekyll-cv-test/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
